#!/usr/bin/env bash

BASE_URL="${BASE_URL:-http://127.0.0.1:8000}"
TEST_EMAIL_PREFIX="test"
TEST_EMAIL_DOMAIN="example.com"
TIMESTAMP=$(date +%s)

TEST_EMAIL="${TEST_EMAIL_PREFIX}${TIMESTAMP}@${TEST_EMAIL_DOMAIN}"
TEST_PASSWORD="TestPass123"

export BASE_URL TEST_EMAIL_PREFIX TEST_EMAIL_DOMAIN TEST_EMAIL TEST_PASSWORD

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

export BASE_URL
export TEST_EMAIL
export TEST_PASSWORD
export RED GREEN YELLOW NC

